### ISSUE TITLE
 Interpreting the output of DGEMO

### ISSUE THREAD

**Issue by Navid-visual** [yunshengtian/DGEMO#2]
Hi,
I am having trouble interpreting the output of DGEMO algorithm (EvaluatedSamples/ParetoFrontEvaluated/ParetoFrontApproximation).csv
Where can I find more information about the meaning of these outputs? my guess is 'ParetoFrontApproximation' is the value that is returned by the surrogate model and 'ParetoFrontEvaluated' are the actual value of pareto set when evaluating the actual function, am I right? 
But I have no idea about 'EvaluatedSamples'.
I would appreciate if you refer me to a source where I can find more information.

**Comment by yunshengtian** [comment]
Hi @Navid-visual, sorry about the confusion! We currently do not have a detailed illustration of these outputs, but you can find more information in _visualization/data_export.py_, where it shows how the result data are exported and what are the source variables of values in these CSV files. You should especially look at the _update()_ function in this file.

And you are right, _ParetoFrontApproximation.csv_ includes the approximated Pareto front found by optimizing on the surrogate model in each iteration, i.e. it's just a guess from the surrogate model and it might not be the actual Pareto front. _ParetoFrontEvaluated.csv_ includes the actual Pareto front in each iteration evaluated by the real evaluation function. For _EvaluatedSamples.csv_, it simply records all the samples evaluated by the real evaluation function, regardless of whether they are Pareto-optimal or not. 

Hope this addresses your concern, and let me know if you have further questions!

**Comment by Navid-visual** [comment]
Thank you for your quick response. according to your explaination in order to get the final paretofront we need to read the output of the last iteration in ParetoFrontEvaluated.csv, right?

**Comment by yunshengtian** [comment]
Correct!

**Comment by Navid-visual** [comment]
Great, thank you.
