### ISSUE TITLE
AttributeError: 'GaussianProcessRegressor' object has no attribute '_K_inv'

### ISSUE THREAD

**Issue by sustech-lz** [yunshengtian/DGEMO#7]

**Comment by ZhengLI-Sustech** [comment]
Thank you very much for answering my question last time, but I still encountered some problems when actually running the main() function. When we imported the GaussianProcessRegressor module from sklearn, we did not find the _K_inv function in it. Excuse me. What can be used to solve this problem?

**Comment by yunshengtian** [comment]
I believe this is the package version problem. Make sure you use the same version of packages as we detailed in the environment.yml.
